# Generated by Django 4.0.2 on 2022-05-21 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categoryItems/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', related_query_name='my goods', to='delivery.categoryitem'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='avatar',
            field=models.ImageField(null=True, upload_to='shippers/%Y/%m'),
        ),
    ]
