# Generated by Django 4.0.2 on 2022-04-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='images',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orderList/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashtags',
            field=models.ManyToManyField(to='delivery.Hashtag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
