# Generated by Django 4.0.3 on 2022-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(null=True, upload_to='customer/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='avatar',
            field=models.ImageField(null=True, upload_to='customer/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='product/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user/%Y/%m'),
        ),
    ]
