# Generated by Django 4.0.2 on 2022-05-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_categoryitem_image_alter_goods_category_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodss', related_query_name='my goods', to='delivery.categoryitem'),
        ),
    ]
