# Generated by Django 4.0.3 on 2022-03-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_list',
            new_name='OrderList',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='deliver',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='orderlist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='order_list',
            new_name='orderList',
        ),
        migrations.AlterField(
            model_name='deliver',
            name='avatar',
            field=models.ImageField(null=True, upload_to='deliver/%Y/%m'),
        ),
    ]
