# Generated by Django 4.0.3 on 2022-03-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_rename_order_list_orderlist_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='images',
            field=models.ImageField(null=True, upload_to='orderList/%Y/%m'),
        ),
    ]
